image: 
  file: .gitpod.Dockerfile

tasks:
  - name: TimerX
    init: pip install -r requirements.txt
    command: python main.py
# PS: App doesn't work here since "_tkinter" is unavailable

  - name: Website
    before: cd docs && nvm install 14
    init: yarn install
    command: yarn start
  
  - name: Initialize `cz` and `pre-commit`
    init: pip install -r requirements-dev.txt
    command: pre-commit install && pre-commit run

ports:
  - port: 3000
    onOpen: ignore
  - port: 4000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - silvenon.mdx
