image: 
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r requirements.txt
    command: python main.py

ports:
  - port: 3000
    onOpen: ignore
  - port: 4000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python