repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.3
 
- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3.8