name: Formatting

on:
  push:
    branches: [master]


jobs:
  Formatting:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python -m pip install black
          python -m pip install isort
      - name: Format code
        run: |
          python -m black main.py
          python -m isort main.py
