name: Build Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |

          pip install -r packager-requirements.txt
      - name: Run cx_Freeze

        run: |
          python setup.py bdist_msi
          
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements-dev.txt
      - name: Run cx_freeze
        run: |
          python setup.py bdist_dmg    
