name: Build Workflow

on: workflow_dispatch,
  push:
    branches: master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller main.spec
  
