name: Release Build for Ubuntu

on:
  workflow_dispatch:
    inputs:
      version-ubuntu:
        description: 'Version(semver)'
        required: true
        default: '1.0'
        

jobs:

# UBUNTU BUILD
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r packager-requirements.txt

      - name: Run cx_freeze 
        continue-on-error: true
        run: |
          python setup.py bdist_rpm

      - name: Run alien
        continue-on-error: true
        run: |
          cd dist
          sudo apt install alien
          sudo alien -d TimerX-${{ github.event.inputs.version-ubuntu }}.tar.gz --version=1.0
          sudo alien -r TimerX-${{ github.event.inputs.version-ubuntu }}.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: TimerX-deb
          path: dist/timerx_${{ github.event.inputs.version-ubuntu }}-2_all.deb
      - uses: actions/upload-artifact@v2
        with:
          name: TimerX-rpm
          path: dist/timerx_${{ github.event.inputs.version-ubuntu }}-2_all.rpm
          
#RELEASE UBUNTU
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version-ubuntu }}
          release_name: 'Release ${{ github.event.inputs.version-ubuntu }}'
          overwrite: true
          body: |
            Release ${{ github.event.inputs.version-ubuntu }} (Add your content here and then publish this.)
          draft: true
          prerelease: false
      - name: Upload Release Asset(Deb)
        id: upload-release-asset-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/timerx_${{ github.event.inputs.version-ubuntu }}-2_all.deb
          asset_name: TimerX-deb
          asset_content_type: application/zip          

      - name: Upload Release Asset(Rpm)
        id: upload-release-asset-rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/timerx_${{ github.event.inputs.version-ubuntu }}-2_all.rpm
          asset_name: TimerX-rpm
          asset_content_type: application/zip         
