#MACOS
  build-macos:
  
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r packager-requirements.txt
      - name: Run PyInstaller
        run: |
          python setup.py bdist_dmg
      - uses: actions/upload-artifact@v2
        with:
          name: TimerX
          path: build/TimerX.dmg
