name: Release Build for TimerX

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '1.0'
        

jobs:

# UBUNTU BUILD
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r packager-requirements.txt

      - name: Run cx_freeze 
        continue-on-error: true
        run: |
          python setup.py bdist_rpm

      - name: Run alien
        continue-on-error: true
        run: |
          cd dist
          sudo apt install alien
          sudo alien -d TimerX-${{ github.event.inputs.version }}.tar.gz --version=1.0
          sudo alien -r TimerX-${{ github.event.inputs.version }}.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: TimerX-deb
          path: dist/timerx_${{ github.event.inputs.version }}-2_all.deb
      - uses: actions/upload-artifact@v2
        with:
          name: TimerX-rpm
          path: dist/TimerX-${{ github.event.inputs.version }}-2.noarch.rpm
          
#RELEASE
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: 'Release ${{ github.event.inputs.version }}'
          overwrite: true
          body: |
            Release ${{ github.event.inputs.version }} (Add your content here and then publish this.)
          draft: true
          prerelease: false
      - name: Upload Release Asset(DEB)
        id: upload-release-asset-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/timerx_${{ github.event.inputs.version }}-2_all.deb
          asset_name: TimerX-deb
          asset_content_type: application/zip          

      - name: Upload Release Asset(RPM)
        id: upload-release-asset-rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/TimerX-${{ github.event.inputs.version }}-2.noarch.rpm
          asset_name: TimerX-rpm
          asset_content_type: application/zip         
